# This is a config for E2B sandbox template.
# You can use template ID (86yglrmekflha7x2mgyf) or template name (bug-hug) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("bug-hug") # Sync sandbox
# sandbox = await AsyncSandbox.create("bug-hug") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('bug-hug')

team_id = "4d12d060-b3de-4e34-ab2b-3db742b5eb61"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "bug-hug"
template_id = "86yglrmekflha7x2mgyf"
